<?php require './templates/header.template.phtml';?>

<div class="d-flex justify-content-center align-items-center my-4">
<div class="p-4 border rounded">
<table class="table table-borderless">
      <thead>
        <tr>
        <th scope="col">Id</th>
          <th scope="col">Name</th>
          <th scope="col">Email</th>
          <th scope="col">Address</th>
          <th scope="col">Phone</th>
          <th scope="col">Image</th>
        </tr>
      </thead>

      <tbody>
        <?php foreach($clients as $client): ?>
          <tr>
            <th scope="row"> <?= $client->id_client ?></th>
            <td><?= $client->name ?></td>     
            <td><?= $client->email ?></td>
            <td><?= $client->addres ?> </td>
            <td> <?= $client->phone ?></td>
            <td>
                <?php if (empty($client->image)): ?>
                      No hay imagen adjuntada
                <?php else: ?>
                    <img src="<?= $client->image ?>" alt="Imagen del cliente" style="width: 70px; height: auto;" class= "rounded">
                <?php endif; ?>
            </td>
                <?php if (!empty($_SESSION['ID_USER'])): ?>
            <td><a href="<?= BASE_URL ?>deleteClient/<?=$client->id_client?>"> <button method = "post" type="button" class="btn btn-primary">Eliminar cliente</button></a></td>
            <td><a href="<?= BASE_URL ?>modifyClient/<?=$client->id_client?>"> <button method = "post" type="button" class="btn btn-primary">Actualizar cliente</button></a></td>
                <?php endif; ?>
            <td><a href="<?= BASE_URL ?>showClient/<?=$client->id_client?>"> <button method = "post" type="button" class="btn btn-primary">Ver pedidos</button></a></td>
          </tr>  
        
        <?php endforeach;?>
        <?php if (!empty($_SESSION['ID_USER'])): ?>
        <td><a href="<?= BASE_URL ?>addClient/"> <button method ="post" type="button" class="btn btn-primary">Añadir cliente</button></a></td>
        <?php endif; ?>
    </tbody>
</table>
</div>
</div>

<?php require './templates/footer.template.phtml'?> 

    