<?php require './templates/header.template.phtml';    ?>

<div class="d-flex justify-content-center align-items-center my-4">
    <div class="p-4 border rounded">
        <form action="<?= BASE_URL ?>newClient" method="POST">
                
            <input type="hidden" name="id_client" value="<?php echo isset($client->id_client) ? $client->id_client : ''; ?>">
                <div class="form-group mb-3">
                    <label for="name">Ingrese nombre</label> 
                        <input type="text" class="form-control" id="name" name="name" value="<?php echo isset($client->name) ? $client->name : ''; ?>" required>
                    <label for="email">Ingrese email</label>
                        <input type="email" class="form-control" id="email" name="email" value="<?php echo isset($client->email) ? $client->email : ''; ?>" required>
                    <label for="addres">Ingrese dirección</label>
                        <input type="text" class="form-control" id="addres" name="addres" value="<?php echo isset($client->addres) ? $client->addres : ''; ?>" required>
                    <label for="phone">Ingrese teléfono</label>
                    <input type="number" class="form-control" id="phone" name="phone" value="<?php echo isset($client->phone) ? $client->phone : ''; ?>" required>
                    <!----<label for="phone">Adjunte archivo</label>
                        <input type="file" class="form-control" id="file" name="file">---->
                </div>

                <button type="submit" class="btn btn-warning">
                    <?php echo isset($client->id_client) ? 'Actualizar Cliente' : 'Añadir Cliente'; ?>
                </button>
        </form>

        <div class="mt-3">            
            <a href="../showClients" class="btn btn-warning">Volver</a>
        </div>

    </div>
    
</div>

<?php require './templates/footer.template.phtml'?> 