<?php require './templates/header.template.phtml';    ?>

<div class="d-flex justify-content-center align-items-center my-4">
    <div class="p-4 border rounded">
        <form action="addNewClient" method="POST">
            <div class="form-group">
                <label for="name">Ingrese su nombre:</label>
                <input type="text" class="form-control" id="name" name="name" required><br><br>
                <label for="email">Ingrese su email:</label>
                <input type="email" class="form-control" id="email" name="email" required><br><br>
                <label for="addres">Ingrese su dirección:</label>
                <input type="text" class="form-control" id="addres" name="addres" required><br><br>
                <label for="phone">Ingrese su teléfono:</label>
                <input type="number" class="form-control" id="phone" name="phone" required><br><br>
            </div>
            <button type="submit" class="btn btn-warning"> Añadir cliente</button>
        </form>
        <div class="mt-3">            
            <a href="../showClients" class="btn btn-warning">Volver</a>
        </div>
    </div>
</div>

<?php require './templates/footer.template.phtml'?> 