<?php require './templates/header.template.phtml';    ?>


<div class="d-flex justify-content-center align-items-center my-4">
    <div class="p-4 border rounded">
        <form action = "updateOrder"  method="POST">
            <div class="form-group">
                <label for="date">Fecha</label>
                <input type="date" class="form-control" id="date" name="date" required> 
                <label for="status">Estado</label>  
                <select class="form-control" id="status" name="status" required>
                    <option value="pendiente">Pendiente</option>
                    <option value="en preparacion">En preparacion</option>
                    <option value="en camino">En camino</option>
                    <option value="entregado">Entregado</option>
                </select>

                <label for="id_client">Id Cliente</label> 
                <select name="id_client">                    
                    <?php foreach($clients as $client): ?>
                        <option value="<?= $client->id_client ?>"><?= $client->name ?></option>
                    <?php endforeach; ?>
                </select>      
                
            </div>
            
            <button type="submit"   class="btn btn-primary mt-4">Agregar Pedido</button> 
            <div><a href="../showOrders"><button  type="button" class="btn btn-warning">Volver</button></a> </div>
            

</form>
<?php require './templates/footer.template.phtml'?> 