<?php require './templates/header.template.phtml';    ?>


<div class="d-flex justify-content-center align-items-center my-4">
    <div class="p-4 border rounded">
        <form action= "newOrder"  method="POST">
            <div class="form-group
            ">
                <label for="date">Fecha</label>
                <input type="text" class="form-control" id="date" name="date" required> 
                <label for="status">Estado</label>  
                <select class="form-control" id="status" name="status" required>
                    <option value="pendiente">Pendiente</option>
                    <option value="en preparacion">En preparacion</option>
                    <option value="en camino">En camino</option>
                    <option value="entregado">Entregado</option>
                </select>
                <label for="id_client">Id Cliente</label>       
                <input type="text" class="form-control" id="id_client" name="id_client" required>   
            </div>
            
            <button type="submit"   class="btn btn-primary mt-4">Agregar Pedido</button> 
            

</form>