<?php require './templates/header.template.phtml'; ?>

<div class="d-flex justify-content-center align-items-center my-4">
    <div class="p-4 border rounded">
        
        <form action="<?= BASE_URL ?><?= isset($order[0]->id_order) ? 'updateOrder' : 'newOrder' ?>" method="POST" enctype="multipart/form-data">
        
            <input type="hidden" name="id_order" value="<?= isset($order[0]->id_order) ? $order[0]->id_order : ''; ?>">

            <div class="form-group">
                <label for="date">Fecha</label>
                <input type="date" class="form-control" id="date" name="date" value="<?= isset($order[0]->date) ? $order[0]->date : ''; ?>">

                <label for="status">Estado</label>
                <select class="form-control" id="status" name="status" required>
                    <option value="pendiente" <?= isset($order[0]->status) && $order[0]->status == 'pendiente' ? 'selected' : '' ?>>Pendiente</option>
                    <option value="en preparacion" <?= isset($order[0]->status) && $order[0]->status == 'en preparacion' ? 'selected' : '' ?>>En preparación</option>
                    <option value="en camino" <?= isset($order[0]->status) && $order[0]->status == 'en camino' ? 'selected' : '' ?>>En camino</option>
                    <option value="entregado" <?= isset($order[0]->status) && $order[0]->status == 'entregado' ? 'selected' : '' ?>>Entregado</option>
                </select>

                <label for="id_client">Cliente</label>
                <select class="form-control" id="id_client" name="id_client" required>
                    <?php foreach ($clients as $client): ?>
                        <option value="<?= $client->id_client ?>" <?= isset($order[0]->id_client) && $order[0]->id_client == $client->id_client ? 'selected' : '' ?>>
                            <?= $client->name ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>

            <button type="submit" class="btn btn-outline-danger mb-3 mt-3">
                <?= isset($order[0]->id_order) ? 'Modificar Pedido' : 'Agregar Pedido'; ?>
            </button>
            
            
        </form>

        <div>
            <a href="<?= BASE_URL ?>showOrders">
                <button type="button" class="btn btn-outline-danger ml-2">Volver</button>
            </a>
        </div>
    </div>
</div>
</form>
<?php require './templates/footer.template.phtml'; ?>
