<?php

if (session_status() === PHP_SESSION_NONE) {
    session_start();
}
$res = !empty($_SESSION['USERNAME']);
?>

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Tedexter</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>

  <body class="d-flex flex-column min-vh-100"> 
    
  <nav class="navbar navbar-expand-lg bd-navbar sticky-top"  style="background: linear-gradient(135deg, #ff5733, #c70039); color: white;">
  <div class="container-xxl bd-gutter flex-wrap flex-lg-nowrap">
    <a class="navbar-brand text-white"  href="<?= BASE_URL ?>home">TeDexter</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link text-white" aria-current="page" href="<?= BASE_URL ?>home">Inicio</a>
        <a class="nav-link text-white" href="<?= BASE_URL ?>showClients">Usuarios</a>
        <a class="nav-link text-white" href="<?= BASE_URL ?>showOrders">Pedidos</a>
      </div>
      <div class="ms-auto"> <!-- Clase para alinear a la derecha -->
        <?php if (!empty($_SESSION['USERNAME'])): ?>
            <a class=" btn btn-outline-light px-4" href="<?= BASE_URL ?>logOut">Log out</a>  
        <?php else: ?>
            <a class=" btn btn-outline-light px-4" href="<?= BASE_URL ?>login">Log in</a> <!-- Botón con estilo -->
        <?php endif; ?>
        <body class="d-flex flex-column min-vh-100"> 

    </div>
  </div>
</nav>