<?php require './templates/header.template.phtml' ?>
<div class="container">
    <div class="row">
        <div class="col-12">
            <img src="img/teDexter.jpg" class="img-fluid" alt="Imagen de la tienda TeDEXter">
            <h1 class="text-center">Bienvenido a la tienda  TeDEXter</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <p class="text-center">Aquí podrás encontrar una gran variedad indumetaria para todos los deportes  .</p>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <p class="text-center">¡Seguro que encontras lo que buscas!</p>
        </div>
    </div>