
<?php require './templates/header.template.phtml' ?>

<body>
<form method= 'POST' action='<?= BASE_URL ?>login'>
  <div class="container mt-5">
    <div class="bg-white p-5 rounded-5 text-secondary shadow mx-auto" style="width: 25rem">
      <div class="d-flex justify-content-center">
      <svg class="mx-auto my-3" xmlns="http://www.w3.org/2000/svg" width="80" height="80" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
                  <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6"/>
                </svg>
      </div>

      <div class="text-center fs-1 fw-bold">Login</div>
        <div class="input-group mt-4">
          <div class="input-group-text text-secondary mx-auto">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
              <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6"/>
            </svg>
          </div>
          <input type="text" class="form-control bg-light" placeholder="Username" id="username" name="username" required/>
        </div>

        <div class="input-group mt-1">
          <div class="input-group-text text-secondary mx-auto">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-key-fill" viewBox="0 0 16 16">
              <path d="M3.5 11.5a3.5 3.5 0 1 1 3.163-5H14L15.5 8 14 9.5l-1-1-1 1-1-1-1 1-1-1-1 1H6.663a3.5 3.5 0 0 1-3.163 2M2.5 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2"/>
            </svg>
          </div>
          <input type="password" class="form-control bg-light" id="password" name="password" placeholder="Password" required>
        </div>

        <button type="submit" class="btn btn-success text-white w-100 mt-4 fw-semibold shadow-sm">Log in</button>

        <?php if ($error): ?> 
            <div class='alert alert-danger mt-3 p-2 small text-center' role='alert'> 
              <?=$error ?>
            </div>
        <?php endif ?>
      </div>
    </div>
  </form>

</body>


<?php require './templates/footer.template.phtml'?> 