
<?php require './templates/header.template.phtml' ?>

<div style="display: flex; justify-content: center; align-items: center; ">   


<!--en caso de haber error lo muestra abajo del form---->

<form method= 'POST' action='login'>

  <div class="mb-3">
    
    <label for="username" class="form-label">Usuario</label>
    <input type="text" class="form-control" id="username" name="username" aria-describedby="emailHelp" required>
    
  </div>

  <div class="mb-3">
    <label for="password" class="form-label">Contraseña</label>
    <input type="password" class="form-control" id="password" name="password" required>
  </div>  

  <button type="submit" class="btn btn-success">Iniciar sesión</button>
  </div>
</form>
<div>

<?php if ($error): ?> 
  <div class='alert alert-danger' role='alert'> 
      <?=$error ?>
  </div>
<?php endif ?>
<?php require './templates/footer.template.phtml'?> 