
<?php require './templates/header.template.phtml' ?>

<div style="display: flex; justify-content: center; align-items: center; ">   

<form>
  <div class="mb-3">
    <label>Usuario</label>
    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Contraseña</label>
    <input type="password" class="form-control" id="exampleInputPassword1">
  </div>  
  <button type="submit" class="btn btn-primary">Submit</button>
  </div>
</form>
<div>