<?php require './templates/header.template.phtml'?>
<div class="container my-4 mt-5">
    <div class="text-center">
        <h2>Bienvenido a la Gestión de Órdenes</h2>
        <p class="mt-3">En esta sección podrás visualizar todas las ordenes registradas en nuestra tienda. Puedes ver la informacion de cada una, y también podés ver los clientes que las realizaron.</p>
    </div>
</div>

<div class="d-flex justify-content-center align-items-center mb-5">
    <div class="p-4 border rounded">
    <table class="table table-borderless">
        <thead>
          <tr>
            <th scope="col">#Order</th>            
            <th scope="col">Status</th>            
            <th scope="col"> Detalles</th>
            <?php if (!empty($_SESSION['USERNAME'])): ?>
            <th scope="col">Modificar</th>  
            <th scope="col">Eliminar</th> 
            <?php endif ?>
          </tr>
        </thead>
        <tbody>
    <?php foreach($orders as $order): ?>
    <tr>
      <th scope="row"> <?= $order->id_order ?></th>           
      <td><?= $order->status ?> </td>      
      <td><a href="<?= BASE_URL ?>showOrder/<?=$order->id_order ?>"> <button method = "post" type="button" class="btn btn-outline-danger">Detalle</button></a></td>
      <?php if (!empty($_SESSION['USERNAME'])): ?>
      <td><a href="<?= BASE_URL ?>formNewOrder/<?=$order->id_order ?>"> <button method = "post" type="button" class="btn btn-outline-danger">Modificar</button></a></td>
      <td><a href="<?= BASE_URL ?>deleteOrder/<?=$order->id_order ?>"> <button method = "post" type="button" class="btn btn-outline-danger">Eliminar</button></a></td>
      <?php endif ?>

    </tr>  
        
<?php endforeach ?>
</tbody>
</table>

<?php if (!empty($_SESSION['USERNAME'])): ?>
<a href="<?= BASE_URL ?>formNewOrder/"> <button method = "post" type="button" class="btn btn-outline-danger">Agregar Pedido</button></a></td>
<?php endif ?>


    

</div>
</div>

<?php require './templates/footer.template.phtml'?> 

