<?php require './templates/header.template.phtml'?>

<div class="d-flex justify-content-center align-items-center my-4">
    <div class="p-4 border rounded">
    <table class="table table-borderless">
        <thead>
          <tr>
            <th scope="col">#Order</th>            
            <th scope="col">Status</th>            
            <th scope="col"> Detalles</th>
            <?php if (isset($_SESSION['IS_LOGGED']) && $_SESSION['IS_LOGGED']): ?>
            <th scope="col">Modificar</th>  
            <th scope="col">Eliminar</th> 
            <?php endif ?>
          </tr>
        </thead>
        <tbody>
    <?php foreach($orders as $order): ?>
    <tr>
      <th scope="row"> <?= $order->id_order ?></th>           
      <td><?= $order->status ?> </td>      
      <td><a href="./showOrder/<?=$order->id_order ?>"> <button method = "post" type="button" class="btn btn-primary">Detalle</button></a></td>
      <?php if (isset($_SESSION['IS_LOGGED']) && $_SESSION['IS_LOGGED']): ?>
      <td><a href="./formNewOrder/<?=$order->id_order ?>"> <button method = "post" type="button" class="btn btn-primary">Modificar</button></a></td>
      <td><a href="./deleteOrder/<?=$order->id_order ?>"> <button method = "post" type="button" class="btn btn-primary">Eliminar</button></a></td>
      <?php endif ?>

    </tr>  
        
<?php endforeach ?>
</tbody>
</table>

<?php if (isset($_SESSION['IS_LOGGED']) && $_SESSION['IS_LOGGED']): ?>
<a href="./formNewOrder"> <button method = "post" type="button" class="btn btn-primary">Agregar Pedido</button></a></td>
<?php endif ?>


    

</div>
</div>

<?php require './templates/footer.template.phtml'?> 

