<?php require './templates/header.template.phtml' ?>
<div class="container my-4 mt-5">
    <div class="text-center">
        <h2>Has elegido ver una orden en especifico!</h2>
        <p class="mt-3">En esta sección podrás visualizar la informacion de los pedidos de <?= $client-> name ?></h3></p>
      </div>
</div>

<div class="d-flex justify-content-center align-items-center">
    <div class="p-4 border rounded">
        <table class="table table-borderless">
          <thead>
            <tr>
              <th scope="col">#Order</th>
              <th scope="col">Date</th>
              <th scope="col">Status</th>
              <th scope="col">#Client</th>
            </tr>
          </thead>
<tbody>
        <h3>Cliente : <?= $client-> name ?></h3>

  <?php foreach($orders as $order): ?>
    <tr>
      <th scope="row"> <?= $order->id_order ?></th>     
      <td><?= $order->date ?></td>
      <td><?= $order-> status?> </td>
      <td> <?= $order->id_client ?></td>
    </tr>  
  <?php endforeach ?>
</tbody>
</table>

<div class="mt-3">
<a href="<?= BASE_URL ?>showOrders"><button  type="button" class="btn btn-outline-danger">Volver</button></a>
  </div>
  </div>
  </div>
<?php require './templates/footer.template.phtml'?> 