<?php require './templates/header.template.phtml'?>

   <table class="table">
        <thead>
          <tr>
            <th scope="col">#Order</th>
            <th scope="col">Date</th>
            <th scope="col">#Client</th>
            <th scope="col">Status</th>
          </tr>
        </thead>
        <tbody>
    <?php foreach($orders as $order): ?>
    <tr>
      <th scope="row"> <?= $order->id_order ?></th>     
      <td><?= $order->date ?></td>
      <td><?= $order->id_client ?> </td>
      <td> <?= $order->status ?></td>
      <td><a href="showOrder/<?=$order->id_order ?>"> <button method = "post" type="button" class="btn btn-primary">Detalle</button></a></td>
    </tr>  
        
<?php endforeach ?>
</tbody>
</table>


<p class="mt-3"><small>Show  <?=$count?> Orders</small></p>

