<?php require './templates/header.template.phtml' ?>

<div class="d-flex justify-content-center align-items-center my-4">
    <div class="p-4 border rounded">
    <table class="table table-borderless">
          <thead>
            <tr>
              <th scope="col">#Order</th>
              <th scope="col">Date</th>
              <th scope="col">Status</th>
              <th scope="col">#Client</th>
            </tr>
          </thead>
        <tbody>

  <?php foreach($orders as $order): ?>
    <tr>
      <th scope="row"> <?= $order->id_order ?></th>     
      <td><?= $order->date ?></td>
      <td><?= $order-> status?> </td>
      <td> <?= $order->id_client ?></td>
      
    </tr>  
        
<?php endforeach ?>
</tbody>
</table>
<a href="../showOrders"><button  type="button" class="btn btn-warning">Volver</button></a>

<?php require './templates/footer.template.phtml'?> 