<?php require './templates/header.template.phtml' ?>


   <table class="table">
        <thead>
          <tr>
            <th scope="col">#Order</th>
            <th scope="col">Date</th>
            <th scope="col">#Client</th>
            <th scope="col">Status</th>
          </tr>
        </thead>
        <tbody>
<?php foreach($orders as $order): ?>
    <tr>
      <th scope="row"> <?= $order->id_order ?></th>     
      <td><?= $order->date ?></td>
      <td><?= $order->id_client ?> </td>
      <td> <?= $order->status ?></td>
      
    </tr>  
        
<?php endforeach ?>
</tbody>
</table>
<a href="../showOrders"><button  type="button" class="btn btn-warning">Volver</button></a>